// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwKZniXvzvFC_emxVZaPR4FVJFI2AfFfo',
    appId: '1:348680274283:web:974751151c18ef32ca8c2e',
    messagingSenderId: '348680274283',
    projectId: 'final-capstone-project-f8bdd',
    authDomain: 'final-capstone-project-f8bdd.firebaseapp.com',
    databaseURL: 'https://final-capstone-project-f8bdd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'final-capstone-project-f8bdd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_kES-S_Kg6loaZmTIQdlTjs9danQqAoM',
    appId: '1:348680274283:android:06dced16dd373f02ca8c2e',
    messagingSenderId: '348680274283',
    projectId: 'final-capstone-project-f8bdd',
    databaseURL: 'https://final-capstone-project-f8bdd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'final-capstone-project-f8bdd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA52UONew0dnljD5YI5qPWarvqoWPHrk08',
    appId: '1:348680274283:ios:af97b536a62d4191ca8c2e',
    messagingSenderId: '348680274283',
    projectId: 'final-capstone-project-f8bdd',
    databaseURL: 'https://final-capstone-project-f8bdd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'final-capstone-project-f8bdd.appspot.com',
    iosBundleId: 'com.facs.facsMobile',
  );
}
