   name: facs_mobile

   on:
     push:
       branches: [ main ]
     pull_request:
       branches: [ main ]

   jobs:
     build:
       runs-on: ubuntu-latest

       steps:
       - uses: actions/checkout@v2
       
       - name: Set up JDK 1.8
         uses: actions/setup-java@v1
         with:
           java-version: 1.8

       - name: Install Flutter
         uses: subosito/flutter-action@v1
         with:
           flutter-version: '3.x.x'

       - name: Get dependencies
         run: flutter pub get

       - name: Build APK
         run: flutter build apk --release

       - name: Upload APK
         uses: actions/upload-artifact@v2
         with:
           name: facs_mobile
           path: build/app/outputs/flutter-apk/facs_mobile.apk