name: facs_mobile
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Set Up Java
        uses: actions/setup-java@v3.12.0
        with:
          distribution: oracle
          java-version: '17'
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: master
          flutter-version: 3.20.0-7.0.pre.38
      - run: flutter pub get
      - run: flutter build apk
      - run: flutter build appbundle
